-keep class io.github.supermonster003.autojs6.plugin.paddleocr.v6.** { *; }
-keep class org.autojs.plugin.** { *; }
-keep class com.paddle.ocr.** { *; }
-keep class ai.onnxruntime.** { *; }
-keep class org.opencv.** { *; }
